name: Release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      APP_NAME: 12_ft
    runs-on: ubuntu-latest
    permissions: write-all
    name: Create GH Release
    steps:
      - uses: actions/checkout@v3
      - name: Build Artifacts
        run: |
          sudo apt install zip
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python build.py
          zip -r umodel_tools.zip umodel_tools

      - name: Create Release
        run: gh release create ${GITHUB_REF#refs/*/} -t ${GITHUB_REF#refs/*/} umodel_tools.zip --generate-notes